# Generated by Django 6.0.4 on 2026-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_admin_runner", "0002_commandexecution_result_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("group", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("app_label", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),  # type: ignore[assignment]
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registered Command",
                "ordering": ["group", "name"],
            },
        ),
    ]
