# Generated by Django 6.0.4 on 2026-04-12 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_admin_runner", "0003_registeredcommand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commandexecution",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
            },
        ),
        migrations.AlterModelOptions(
            name="registeredcommand",
            options={
                "ordering": ["group", "name"],
                "verbose_name": "Command",
                "verbose_name_plural": "Commands",
            },
        ),
    ]
