# Generated by Django 6.0.3 on 2026-08-03 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_admin_runner", "0004_alter_commandexecution_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commandexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "SUCCESS", "FAILED"])),
                name="django_admin_runner_commandexecution_status_valid",
            ),
        ),
    ]
